sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
  - "5.0"
  - "4.2"
install:
  - npm install -g codecov
script:
  - npm run ci-test
after_success:
  - bash <(curl -s https://codecov.io/bash)